server:
  port: ${PORT:8080}
spring:
  application:
    name: train
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: statico/**
  datasource:
    url: jdbc:${DATABASE_PATH:postgresql://localhost:5433/train_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin
springdoc:
  show-login-endpoint: true

logging:
  level:
    org.springframework.web: DEBUG








